version: 2.1

orbs:
  node: circleci/node@4.7

jobs: 
  test:
    steps:
      - yarn install
      - yarn test
  build:
    steps:
      - yarn install
      - yarn build

workflows:
  test_and_build:
    jobs:
      - test
      - build
