version: 2.1

orbs:
  node: circleci/node@4.7

jobs: 
  test:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run: yarn install
      - run: yarn build

workflows:
  test_and_build:
    jobs:
      - test
      - build
